# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

fastlane_version '2.47.0'
default_platform :ios

platform :ios do

  app_name = 'PopGames'

  desc 'Runs all the tests'
  lane :test do |options|
    should_open_coverage_report = options[:show_coverage] ? true : false
    scan workspace: "#{app_name}.xcworkspace", scheme: app_name
    slather(
      proj: "#{app_name}.xcodeproj",
      workspace: "#{app_name}.xcworkspace",
      scheme: app_name,
      output_directory: 'Coverage',
      show: should_open_coverage_report,
      simple_output: !should_open_coverage_report,
      html: true)
  end

  desc 'Submit a new Beta Build to Apple TestFlight'
  desc 'This will also make sure the profile is up to date'
  lane :beta do
    # match type: 'appstore'
    gym scheme: app_name
    pilot
  end

  desc 'Deploy a new version to the App Store'
  lane :release do
    # match type: 'appstore'
    # snapshot
    gym scheme: app_name
    deliver force: true
    # frameit
  end

end
